[tool.poetry]
name = "shannonsdemon"
version = "0.1.0"
description = ""
authors = ["williamv0 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
python-binance = "^1.0.12"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
